---
title: "MY RESUME"
author: "lcy"
date: "2020/10/19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Who I am

          Claire (Chenying) Li
cli.mfa2021@london.edu    +44 (0)752 998 3520

EDUCATION

2020 - 2022	London Business School, London, UK
Reading for Masters in Financial Analysis
Future Coursework: Analysis of Financial Statements, Securities Valuation and Financial Modelling, Corporate Finance, Mergers & Acquisitions
Member: Finance Club

2016 - 2020	Wuhan University, Wuhan, China
Experimental Class of Mathematical Finance
B.S. in Mathematics and Applied Mathematics & B.A. in Economics
Awards: Wuhan University Merit Student Scholarship (Top 10%); Outstanding Student Leader Award
 
BUSINESS EXPERIENCE

2020	DEALGLOBE LIMITED, Shanghai, China

M&A Analyst Intern (4 month)
•	Proposed 30 potential financial sponsors and strategic investors based on preference of investing, synergies and deal size for HKEX-listed global leading mobile advertising platform

•	Conducted valuation analysis through comparable companies and precedent transactions for US$255m exchangeable bond issuance of controlling shareholder of advertising platform

•	Analyzed financial performance according to financial statements combining with company’s business model and strategic layout considering $20 mm internal investment opportunity

•	Collaborated with London office on preparation of Confidential Information Memorandum for sell-side advisory for US$1 bn minority stake of a leading Chinese biopharmaceutical company

•	Adjusted revenue build-up referring to commercial due diligence and taking into account impact of coronavirus for US$4.4 bn plasma product provider

2019	CITIC SECURITIES COMPANY LIMITED, Shenzhen, China
 	Investment Banking Analyst Intern (4 month)
 	
•	Drafted presentation material including transaction overview, underlying rationale and valuation proposal for listed securities company’s CNY9 bn acquisition of minority stake in software company and venture capital film

•	Researched VC & PE industry comprehensively in team of three for potential IPO of top Chinese venture capital firm and converted into 87-page report covering industry landscape, listing policy and feasibility of IPO

•	Established database for 50 listed commercial banks’ use of capital instrument in supplementing capital and increasing capital adequacy ratio in domestic and overseas markets

2019	EVERBRIGHT SECURITIES COMPANY LIMITED, Shanghai, China
 	Quantitative Research Summer Analyst (4 month)
 	
•	Delivered two investment value analysis reports for TMT and Consumption ETF products based on liquidity, size, index tracking ability and industrial distribution, fundamentals and performance of index

•	Built factor testing framework to test new price-related factors and optimized through machine learning method using Python, with main working contents covering factor construction, validity analysis and backtesting

2018	GUOTAI JUNAN SECURITIES CO., LTD., Shanghai, China
 	Investment Banking Summer Analyst (3 month)
 	
•	Collected property right information and business archives of subsidiaries, evaluating assets to be transferred for CNY4.1 bn potential IPO and mixed ownership reform of state-owned enterprise

•	Facilitated in interviews with heads of three subsidiaries in due diligence process, assessing historical development and business model; written part of business section in due diligence report
 
ADDITIONAL INFORMATION

•	Chief Violin of Wuhan University Symphony Orchestra: Hosted visits of Utah Philharmonic Orchestra and Technical University of Munich and held three collaborative concerts; Cooperated with 76 members of orchestra in concert tour of more than 10 cities in China

•	Head of General Affairs Department of Wuhan University Econometric Society: Led a team of 12, holding the Second International Symposium on Experimental Economics, seminar involves 21 sessions

•	Teaching assistant for national coach of US Mathematical Olympiad: Worked for Professor Po-Shen Loh in online courses, aiming to promote creative mathematical thinking to children all around the world

•	Languages: Mandarin Chinese (native), English (fluent)

•	Skills: Python, Matlab, Capital IQ, Wind, Bloomberg, SQL, Microsoft Office

•	Interests: Violin performance (Reached professional grade of China Central Conservatory of Music, won the gold award in China International Youth Art Contest), Classical Music, Musicals, Skiing


